# Generated by Django 4.1.7 on 2023-04-19 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='criado_por',
        ),
        migrations.AddField(
            model_name='demanda',
            name='criado_por',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
