# Generated by Django 3.0 on 2023-06-07 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='criado_por',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
