# Generated by Django 4.1.12 on 2023-10-16 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='criado_por',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
