# Generated by Django 4.1.12 on 2023-11-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='produto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
