# Generated by Django 4.1.7 on 2023-04-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_demanda_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
