# Generated by Django 4.1.7 on 2023-04-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_demanda_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='concluida',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
