# Generated by Django 4.1.7 on 2023-04-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_demanda_concluida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='concluida',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
